spring:
  liquibase:
    change-log: classpath:role-service/local/arts346roleconfig/sample_trial/services/role-servicel/db/changelog/changelog-role-service-master.xml
    drop-first: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  hateoas:
    use-hal-as-default-json-media-type: false
server:
  error:
    include-message: always
    include-binding-errors: always
