spring:
  liquibase:
    change-log: ${SPRING_CLOUD_REPO}{SPRING_CLOUD_CONFIG_LABEL}{SERVICE_LOC}/db/changelog/changelog-role-service-master.xml
    drop-first: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  hateoas:
    use-hal-as-default-json-media-type: false
server:
  error:
    include-message: always
    include-binding-errors: always
