management:
  endpoints:
    web:
      exposure:
        include: "*"

#security config

azure:
  activedirectory:
    client-id: f352ce15-0142-4dfa-8e18-801ee6391557
    session-stateless: true
practitioner:
  service:
    endpoint:
      roles: /practitioner/roles
    name: practitioner-service
    uri: http://practitioner-service
role:
  service:
    endpoint:
      exists: /roles/{id}
      paged: /roles/
      role: /roles/{id}
      roles:
        create: /roles
        by:
          ids: roles
      update:
        permissions: /roles/{id}/permissions
    name: role-service
    uri: http://role-service
site:
  service:
    endpoint:
      sites: /sites
    name: site-service
    uri: http://site-service
spring:
  main:
    allow-bean-definition-overriding: true
