name: Validate Trial Config Files
on:
  push

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check changed files
        id: calc_files_diff
        run: |
          git fetch origin main:localmain

          # Gets changed definition files
          # TODO: validate all config files and not just trial's definition.yml
          export FILES=$(git diff --name-only localmain | grep definition.yml)

          echo "Files changed since last commit..."
          echo "$FILES"

          echo "::set-output name=diff::$( echo "$FILES" | tr '\n' ',' | sed '$s/,$/\n/' )"

      # - name: Validate JSON
      #   # if: ${{ steps.calc_files_diff.outputs.diff != '' }}
      #   if: always()
      #   uses: docker://orrosenblatt/validate-json-action:latest
      #   env:
      #     INPUT_SCHEMA: .ci/trial-json-schema.json
      #     # INPUT_JSONS: ${{ steps.calc_files_diff.outputs.diff }}
      #     INPUT_JSONS: sample_trial/definition.json

      # - name: Validate YML2
      #   if: always()
      #   run: |
      #     sudo npm install -g ajv-cli
      #     sudo npm install -g betterAjvErrors
      #     ajv validate -s .ci/trial-json-schema.json -d sample_trial/definition.yml

      - name: Output current branch name & date
        uses: satackey/action-js-inline@release-master
        with:
          # Edit the following line to install packages required to run your script.
          required-packages: fs better-ajv-errors ajv js-yaml
          script: |
            const core = require('@actions/core')
            const Ajv = require('ajv');
            const betterAjvErrors = require('better-ajv-errors');
            const fs = require('fs');
            const yaml = require('js-yaml');

            const ajv = new Ajv.default({ jsonPointers: true });

            
            // Load schema and data
            const schemaContent = fs.readFileSync('.ci/trial-json-schema.json','utf8');
            const schemaJson = JSON.parse(schemaContent);
            const dataContent = fs.readFileSync('sample_trial/definition.yml','utf8');
            const dataObj = yaml.safeLoad(dataContent);

            const validate = ajv.compile(schemaJson);
            const valid = validate(dataObj);

            if (!valid) {
              const output = betterAjvErrors(schemaJson, dataObj, validate.errors);
              console.log(output);
            }
            