name: Validate Trial Config Files
on:
  push

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check changed files
        id: calc_files_diff
        run: |
          git fetch origin main:localmain

          # Gets changed definition files
          # TODO: validate all config files and not just trial's definition.yml
          export FILES=$(git diff --name-only localmain | grep definition.yml)

          echo "Files changed since last commit..."
          echo "$FILES"

          echo "::set-output name=diff::$( echo "$FILES" | tr '\n' ',' | sed '$s/,$/\n/' )"

      - name: Validate YML
        if: always()
        env:
          INPUT_SCHEMA: .ci/trial-json-schema.json
          INPUT_YML:  ${{ steps.calc_files_diff.outputs.diff }}
        run: |
          sudo npm install -g ajv-cli
          for FILE in $(echo $INPUT_YML | sed "s/,/ /g")
          do
               ajv validate -s $INPUT_SCHEMA -d "$FILE"
          done
        